
Table below of recaptures from 2017 Striped Bass tagging at Knights Landing.
Gear type: fkye traps, 8 traps fished throughout the season

Traps numbered sequentially 1-8, with 1 being the northern-most trap and 8 being the southern-most trap.

    ##    TagNum      Recap     Tagged DAL LenTag LenRec  GPY TrapTag TrapRec
    ## 1  292095 2017-05-09 2016-04-13 391     42     53 10.3       1       8
    ## 2  293982 2017-05-11 2017-04-20  21     38     NA   NA       2       8
    ## 3  293761 2017-05-09 2017-04-19  20     39     NA   NA       6       8
    ## 4  293772 2017-05-09 2017-04-19  20     51     51   NA       8       3
    ## 5  Y12290 2017-05-09 2017-04-20  19     40     39   NA       5       8
    ## 6  294393 2017-05-10 2017-04-25  15     45     NA   NA       6       2
    ## 7  293997 2017-05-03 2017-04-20  13     49     NA   NA       5       7
    ## 8  293997 2017-05-02 2017-04-20  12     49     49   NA       5       8
    ## 9  294503 2017-05-09 2017-04-27  12     38     NA   NA       4       7
    ## 10 294982 2017-05-11 2017-05-02   9     43     NA   NA       2       3
    ## 11 294704 2017-05-03 2017-04-27   6     44     NA   NA       6       7
    ## 12 295384 2017-05-10 2017-05-04   6     41     NA   NA       3       3
    ## 13 294333 2017-04-28 2017-04-26   2     44     NA   NA       3       1
    ## 14 294442 2017-04-27 2017-04-26   1     42     NA   NA       3       2
    ## 15 294504 2017-04-28 2017-04-27   1     42     NA   NA       4       3
    ## 16 294561 2017-04-27 2017-04-26   1     44     NA   NA       7       6
    ## 17 294589 2017-04-28 2017-04-27   1     46     NA   NA       4       3
    ## 18 294602 2017-04-28 2017-04-27   1     42     NA   NA       5       2
    ## 19 294645 2017-04-27 2017-04-26   1     43     NA   NA       8       6
    ## 20 294685 2017-04-28 2017-04-27   1     41     NA   NA       5       4
    ## 21 294711 2017-04-28 2017-04-27   1     42     NA   NA       7       6
    ## 22 294878 2017-05-03 2017-05-02   1     42     NA   NA       4       3
    ## 23 294937 2017-05-03 2017-05-02   1     37     NA   NA       2       1
    ## 24 294942 2017-05-03 2017-05-02   1     46     NA   NA       2       1
    ## 25 294955 2017-05-03 2017-05-02   1     38     NA   NA       4       3
    ## 26 295000 2017-05-03 2017-05-02   1     38     NA   NA       4       3
    ## 27 295019 2017-05-03 2017-05-02   1     42     NA   NA       5       4
    ## 28 295050 2017-05-03 2017-05-02   1     42     NA   NA       7       6
    ## 29 295104 2017-05-03 2017-05-02   1     49     NA   NA       8       7
    ## 30 295113 2017-05-03 2017-05-02   1     43     NA   NA       8       6
    ## 31 295137 2017-05-04 2017-05-03   1     43     NA   NA       4       1
    ## 32 295191 2017-05-03 2017-05-02   1     52     NA   NA       8       7
    ## 33 295223 2017-05-04 2017-05-03   1     46     NA   NA       4       2
    ## 34 295263 2017-05-04 2017-05-03   1     42     NA   NA       4       3
    ## 35 295271 2017-05-04 2017-05-03   1     44     NA   NA       5       4
    ## 36 295344 2017-05-04 2017-05-03   1     75     NA   NA       7       6
    ## 37 295830 2017-05-10 2017-05-09   1     39     NA   NA       5       3
    ## 38 295944 2017-05-10 2017-05-09   1     47     NA   NA       5       4
    ## 39 295985 2017-05-10 2017-05-09   1     48     NA   NA       1       2
    ## 40 295991 2017-05-10 2017-05-09   1     45     NA   NA       2       1
    ## 41 296042 2017-05-10 2017-05-09   1     41     NA   NA       5       4
    ## 42 C02213 2017-04-28 2017-04-27   1     45     NA   NA       5       4
    ## 43 C02231 2017-05-03 2017-05-02   1     39     NA   NA       4       3
    ## 44 F02207 2017-04-27 2017-04-26   1     41     NA   NA       4       3
    ## 45 F02232 2017-05-03 2017-05-02   1     41     NA   NA       5       3
    ## 46 F02234 2017-05-03 2017-05-02   1     51     NA   NA       5       4
    ## 47 F02248 2017-05-04 2017-05-03   1     46     NA   NA       8       7
    ## 48 Y12315 2017-04-27 2017-04-26   1     50     NA   NA       5       4
    ## 49 295892 2017-05-10       <NA>  NA     NA     NA   NA      NA       1

Matrix of recaptures by date tagged (rows) & date recaptured (columns). For example, 5 fish tagged on 04-26 were recaptured on 04-27.

    ##        Recap
    ## Tagged  04-27 04-28 05-02 05-03 05-04 05-09 05-10 05-11
    ##   04-19     0     0     0     0     0     2     0     0
    ##   04-20     0     0     1     1     0     1     0     1
    ##   04-25     0     0     0     0     0     0     1     0
    ##   04-26     5     1     0     0     0     0     0     0
    ##   04-27     0     6     0     1     0     1     0     0
    ##   05-02     0     0     0    13     0     0     0     1
    ##   05-03     0     0     0     0     6     0     0     0
    ##   05-04     0     0     0     0     0     0     1     0
    ##   05-09     0     0     0     0     0     0     5     0

Matrix of count of fish by trap number (rows) & tagging action (columns; see below for description). For example, for the season 341 were tagged (tagging action 1) from trap 4.

| Code | TagAction                        |
|------|----------------------------------|
| 1    | tagged                           |
| 2    | recaptured                       |
| 5    | over (no tag, no data)           |
| 6    | fish dead                        |
| 7    | creeled (no tag, data collected) |

    ##     TagAction
    ## Trap   1   2   5   6   7
    ##    1 160   6   4   0  90
    ##    2 225   5   7   1  95
    ##    3 243  13   6   0 112
    ##    4 341   8  10   2 169
    ##    5 560   0  10   0 103
    ##    6 432   6   7   0 730
    ##    7 420   6   7   0 603
    ##    8 531   5   9   0 597

Same as above except by date (tagging date) rather than trap number. For example, on Apr-28 164 Striped Bass were affixed with a Petersen tag (tagged), 7 Striped Bass were recaptured, and 3 Striped Bass were recorded as over.

    ##         TagAction
    ## RelDate    1   2   5   6   7
    ##   Apr-18  88   0   1   0   1
    ##   Apr-19  88   0   0   0   1
    ##   Apr-20 204   0   5   0   0
    ##   Apr-21 140   0   4   0   0
    ##   Apr-25 261   0   7   0   0
    ##   Apr-26 222   0   7   1   0
    ##   Apr-27 197   5   5   0   0
    ##   Apr-28 164   7   3   0   0
    ##   May-02 288   1   4   0   0
    ##   May-03 242  15   5   0   0
    ##   May-04 427   6   6   0  62
    ##   May-09 314   5   5   1 593
    ##   May-10   0   8   3   0 481
    ##   May-11   0   2   1   1 952
    ##   May-16   0   0   0   0 409
    ##   May-17 277   0   4   0   0

Matrix of within-season recaptures by trap tagged (rows) & trap recaptured (columns). Only 1 Striped Bass was recaptured in the same trap it was tagged (trap 3). Fish tagged from trap 5 were recaptured in other traps, but trap 5 did not record any recaptures (sum columns, this was the only trap without a recap).

    ##       Recap
    ## Tagged 1 2 3 4 5 6 7 8
    ##      1 0 1 0 0 0 0 0 0
    ##      2 4 0 1 0 0 0 0 1
    ##      3 1 1 1 0 0 0 0 0
    ##      4 1 1 8 0 0 0 1 0
    ##      5 0 1 2 8 0 0 1 2
    ##      6 0 1 0 0 0 0 1 1
    ##      7 0 0 0 0 0 4 0 0
    ##      8 0 0 1 0 0 2 3 0

Recapture 'rate' - though it's more of a proportion. Matrix above divided (row-wise) by the number of tags per trap.

Tags per trap (in order 1-8): 160, 225, 243, 341, 560, 432, 420, 531

    ##       Recap
    ## Tagged       1       2       3       4       5       6       7       8
    ##      1 0.00000 0.00625 0.00000 0.00000 0.00000 0.00000 0.00000 0.00000
    ##      2 0.01778 0.00000 0.00444 0.00000 0.00000 0.00000 0.00000 0.00444
    ##      3 0.00412 0.00412 0.00412 0.00000 0.00000 0.00000 0.00000 0.00000
    ##      4 0.00293 0.00293 0.02346 0.00000 0.00000 0.00000 0.00293 0.00000
    ##      5 0.00000 0.00179 0.00357 0.01429 0.00000 0.00000 0.00179 0.00357
    ##      6 0.00000 0.00231 0.00000 0.00000 0.00000 0.00000 0.00231 0.00231
    ##      7 0.00000 0.00000 0.00000 0.00000 0.00000 0.00952 0.00000 0.00000
    ##      8 0.00000 0.00000 0.00188 0.00000 0.00000 0.00377 0.00565 0.00000

Visual display of matrix above. Of the Striped Bass collected and then tagged from trap 4 (n=341) some were recaptured in traps 1, 2, 3, & 7. Eight, or ~2.3% (`8/341`), were recaptured in trap 3.

![](MarkRecap-Development_files/figure-markdown_github-ascii_identifiers/rr-viz-1.png)

Display of fraction (by tagging action) of total Striped Bass caught per trap. Trap 5 caught 673 Striped Bass on the season. Of those 560 (~83%) were affixed with a Petersen tag (see 'Tagged').

![](MarkRecap-Development_files/figure-markdown_github-ascii_identifiers/prop-viz-1.png)

------------------------------------------------------------------------

end of report
ran: 2017-07-07 15:05:52
CDFW (2017)
